### ISSUE TITLE
Update error 

### ISSUE THREAD

**Issue by ggsoft** [takezoe/scala-jdbc#5]
Table in postgres:

CREATE TABLE articles (
    id serial PRIMARY KEY,
    published bigint NOT NULL,
    author varchar (50) NOT NULL,
    title varchar (100) NOT NULL,
    text varchar (5000) NOT NULL
    );

java.lang.UnsupportedOperationException: Unsupported type: scala.collection.mutable.WrappedArray$ofRef
        at com.github.takezoe.scala.jdbc.TypeMapper.set(TypeMapper.scala:19)
        at com.github.takezoe.scala.jdbc.DB.$anonfun$execute$2(DB.scala:291)
        at com.github.takezoe.scala.jdbc.DB.$anonfun$execute$2$adapted(DB.scala:290)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at com.github.takezoe.scala.jdbc.DB.$anonfun$execute$1(DB.scala:290)
        at com.github.takezoe.scala.jdbc.IOUtils$.using(IOUtils.scala:28)
        at com.github.takezoe.scala.jdbc.DB.execute(DB.scala:289)
        at com.github.takezoe.scala.jdbc.DB.update(DB.scala:20)
        at app.model.Article$.$anonfun$add$1(Articles.scala:21)
        at app.model.Article$.$anonfun$add$1$adapted(Articles.scala:20)
        at com.github.takezoe.scala.jdbc.DB.autoClose(DB.scala:267)
        at com.github.takezoe.scala.jdbc.DB$.autoClose(DB.scala:13)
        at app.model.Article$.add(Articles.scala:20)

case class Article(val id: Long, val ms: Long, val author: String, val title: String, val text: String)

def add(a: Article) = DB.autoClose(getConnection) { db =>
    db.update(sql"INSERT INTO articles (published,author,title,text) VALUES (${a.ms},${a.author},${a.title},${a.text})")
  }

scala> val a = Article(0l, 1321313l, "author", "title", "text")
a: app.model.Article = Article(0,1321313,author,title,text)

scala> sql"INSERT INTO articles (published,author,title,text) VALUES (${a.ms},${a.author},${a.title},${a.text})"
res0: com.github.takezoe.scala.jdbc.package.SqlTemplate = SqlTemplate(INSERT INTO articles (published,author,title,text) VALUES (?,?,?,?),WrappedArray(WrappedArray(1321313, author, title, text)))

**Comment by ggsoft** [comment]
Nested WrappedArray appear because of using twice Any*
My solution is to write 

SqlTemplate(sql, args:_*) 

instead of 

SqlTemplate(sql, args.toSeq)

in 22th line of file takezoe/scala/jdbc/package.scala

implicit class SqlStringInterpolation(val sc: StringContext) extends AnyVal {
    def sql(args: Any*): SqlTemplate = {
      val sql = sc.parts.mkString("?")
      SqlTemplate(sql, args:_*)
    }
}

**Comment by takezoe** [comment]
@ggsoft Thanks. Fixed and added a test case. I would like to release the next version immediately.

**Comment by takezoe** [comment]
Published 1.0.5!
